"""Add description field to task table

Revision ID: f1b3216e6c1b
Revises: 0b6e959ffdc4
Create Date: 2026-02-03 12:43:40.118813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f1b3216e6c1b'
down_revision: Union[str, None] = '0b6e959ffdc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True, default=""))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'description')
    # ### end Alembic commands ###